### ISSUE TITLE
Make scrollY and scrollX `Number` instead of `Int`

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-web/purescript-web-html#21] opened 2019-10-05 14:44 UTC
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY says that 

> If the document is rendered on a subpixel-precise device, then the returned value is also subpixel-precise and may contain a decimal component.

**Comment by hdgarrood** [comment] 2019-10-05 19:44
Duplicate of #16

**Closed as completed by hdgarrood** 2019-10-05 19:44 UTC

**Comment by i-am-the-slime** [comment] 2019-10-06 08:03
Sorry

**Comment by hdgarrood** [comment] 2019-10-06 14:18
Not a problem! 🙂
